### PR TITLE
Big changes to build.gradle files

### PR DESCRIPTION
**Pull request by MadRatSRP**

### CODE REVIEW

**Review by hoc081098 — CHANGES_REQUESTED** [review]
Thanks for your contribution. I think we should use same dependencies version for all modules, by defining them in root project gradle file.

**Comment by MadRatSRP** [comment]
No problems, please think about adding .gitignore to your project, you can easily exclude at least gradle/ directory and its files, after cloning the project Android Studio will automatically download gradle files

**Comment by MadRatSRP** [comment]
Also, i've got a question about this project's dependencies. After reading this article https://medium.com/@Zhuinden/simple-one-liner-viewbinding-in-fragments-and-activities-with-kotlin-961430c6c07c and comparing its dependencies with yours i saw that your version uses only lifecycle-common-java8 from the AndroidX Jetpack, while the solution in this article uses 4 different lifecycle dependencies:

implementation "androidx.lifecycle:lifecycle-runtime:2.2.0"
implementation "androidx.lifecycle:lifecycle-common-java8:2.2.0"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"

So my question is: which one is better? Is it really okay with depending only on one lifecycle dependencies?

And talking about reflection, is it really that visible for user (usage of viewbinding oneliner with reflection) that i should use the one without reflection? Or its not?

**Comment by MadRatSRP** [comment]
Sorry for disturbing, but when are you planning to confirm my pull request and include it into your project?

**Comment by hoc081098** [comment]
@MadRatSRP I'm a little busy today. Tomorrow i will merged

**Pull request closed without merging**
